### ISSUE TITLE
Version colors doesn't change before restart

### ISSUE THREAD

**Issue by EgilSandfeld** [unitycoder/UnityLauncher#19]
Red -> Green color to show the Unity version is installed is not changed to green after you add your paths to Unity installs. You have to restart Unity Launcher for it to show in green.

**Comment by unitycoder** [comment]
yes, currently after new unity installation have to either
- restart client
- or press F5 in the Unity installations tab (to refresh the list)
- or press Refresh unity list,  in the settings tab

not sure what would other good way to check installation changes (because scanning the whole install folder is bit heavy operation)

**Comment by unitycoder** [comment]
now that unity list tab also has refresh button,
![image](https://user-images.githubusercontent.com/5438317/35469210-accf82c6-036b-11e8-9c18-84b0f401d6e1.png)

**Comment by unitycoder** [comment]
actually when refreshing/scanning unity versions, should refresh recent projects list also (to update version colors in the project list)
