### ISSUE TITLE
Unity launch arguments

### ISSUE THREAD

**Issue by lesinski** [unitycoder/UnityLauncher#4]
It could be nice to have an option to specify launch arguments for different projects.

An use case could be having both a Pro and Personal projects on one machine and have Unity run the latter with '-force-free' argument

**Comment by unitycoder** [comment]
yeah, possible to add.. just need to think of some nice way to do it.

perhaps extra column after LastUpdated in the grid, with editable cell to type any arguments there?

**Comment by lesinski** [comment]
Yeah why not - that could work. The only thing Im afraid of is that it will clutter the view a bit. Maybe a simple text input would be enough?

Regarding visuals, there is an option of replacing/moving the 'Modified' column or maybe adding an extra view (a popup) after right clicking/double clicking on a project?

**Comment by unitycoder** [comment]
ok have one idea for this now that we can resize window and columns..

Save launcharguments.txt (or similar) file under ProjectSettings/ folder,
Benefits of that:
- otherwise we would end up orphaned project settings in memory (if the arguments are saved within launcher, and then project disappears from recent list, or would need to do house keeping to clear old ones)
- launch arguments would be transferred with git/copying project
- can build your own scripts to change launcharguments.txt if want to

**Comment by unitycoder** [comment]
now available in latest build,
Select project row, press F2 to edit arguments, then can launch with those
https://github.com/unitycoder/UnityLauncher/releases
